server:
  port: 8001
spring:
  application:
    name: studentdemo-query-server
    
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceURL:
   defaultZone: http://localhost:7001/eureka

 instance:
  hostname: localhost